/* ケロちゃん ランド in every language: [Tiếng Việt, English, 한국어] (see js/lang.js). */
Lang.add({
  'ケロちゃん ランド': ['Thế giới Kero', 'Kero Land', '케로 랜드'],
  'あそびたい ゲームを えらんでね！': ['Chọn trò chơi nhé!', 'Pick a game to play!', '하고 싶은 게임을 골라 봐!'],
  '{name}、ゲームを えらんでね！': ['{name} ơi, chọn trò chơi nhé!', '{name}, pick a game!', '{name}, 게임을 골라 봐!'],
  'なまえ': ['Tên', 'Name', '이름'],
  'だれが あそぶ？': ['Ai chơi nào?', 'Who is playing?', '누가 할래?'],
  'えらんだ 人で ぜんぶの ゲームを あそぶよ': ['Người được chọn sẽ chơi mọi trò chơi', 'The one you choose plays every game', '고른 사람으로 모든 게임을 해요'],
  'ユーザーを ふやす': ['Thêm người chơi', 'Add a player', '사용자 추가'],
  'ユーザーの せってい': ['Cài đặt người chơi', 'Player settings', '사용자 설정'],
  'こども': ['Trẻ em', 'Child', '어린이'],
  'おとな': ['Người lớn', 'Grown-up', '어른'],
  'なまえなし': ['Chưa có tên', 'No name', '이름 없음'],
  'なおす': ['Sửa', 'Edit', '편집'],
  'けす': ['Xóa', 'Delete', '지우기'],
  'もう一度 おすと けすよ': ['Nhấn lần nữa để xóa', 'Tap again to delete', '한 번 더 누르면 지워져요'],
  'れい：はなこちゃん': ['Ví dụ: Na', 'e.g. Hana', '예: 하나'],
  'やめる': ['Thôi', 'Cancel', '취소'],
  'ホームに ついか': ['Thêm vào màn hình', 'Add to Home', '홈 화면에 추가'],
  'タッチの おと': ['Âm thanh khi chạm', 'Tap sound', '터치 소리'],
  'ことば': ['Ngôn ngữ', 'Language', '언어'],
  'ことばを えらんでね': ['Chọn ngôn ngữ', 'Choose a language', '언어를 골라 주세요'],
  'ぜんぶの ゲームが この ことばに なるよ': ['Mọi trò chơi sẽ dùng ngôn ngữ này', 'Every game will use this language', '모든 게임이 이 언어로 바뀌어요'],
  'とじる': ['Đóng', 'Close', '닫기'],
  'ケロちゃん\nもぐもぐ': ['Kero\nMăm Măm', 'Kero\nMunch Munch', '케로\n냠냠'],
  'ケロちゃん\nぴよぴよポン': ['Kero\nChíp Chíp Bùm', 'Kero\nChick Pop', '케로\n삐약삐약 퐁'],
  'ケロちゃん\nあたま ぐんぐん': ['Kero\nLuyện Não', 'Kero\nBrain Boost', '케로\n두뇌 쑥쑥'],
  'ケロちゃん\nみるみる': ['Kero\nMắt Tinh', 'Kero\nQuick Eyes', '케로\n반짝눈'],
  // moving to the new address (js/move.js; no Korean from 2026-09-30)
  'ケロちゃん ランドは おひっこし したよ！': ['Thế giới Kero đã chuyển nhà rồi!', 'Kero Land has moved!'],
  'あたらしい ばしょで あそんでね。きろくも ぜんぶ もっていくよ。': ['Mình chơi ở nhà mới nhé. Thành tích cũng mang theo hết luôn.', 'Play at the new place. All your records come along too.'],
  'おひっこし する': ['Chuyển nhà', 'Move now'],
  'あたらしい ばしょを ひらいてね。': ['Mở nhà mới ra chơi nhé.', 'Open the new place.'],
  'あたらしい ランドを ひらく': ['Mở Thế giới Kero mới', 'Open the new Kero Land'],
  'きろくを もう いちど おくる': ['Gửi lại thành tích', 'Send the records again'],
  'おひっこし できたよ！': ['Chuyển nhà xong rồi!', 'All moved in!'],
  'きろくも ぜんぶ もってきたよ。': ['Thành tích cũng mang sang hết rồi.', 'All your records are here too.'],
  'この ランドを ホームに ついか して、ふるい ほうは けしてね。': ['Hãy thêm Thế giới Kero này vào màn hình chính, rồi xóa bản cũ nhé.', 'Add this Kero Land to your Home screen, and remove the old one.'],
  'まえの きろくで うわがき する？': ['Ghi đè bằng thành tích cũ?', 'Replace with the old records?'],
  'この スマホの あたらしい ランドには もう きろくが あるよ。うわがき すると いまの きろくは きえるよ。': ['Thế giới Kero mới trên máy này đã có thành tích rồi. Nếu ghi đè thì thành tích hiện tại sẽ mất.', 'The new Kero Land on this phone already has records. Replacing them deletes the ones here now.'],
  'うわがき する': ['Ghi đè', 'Replace'],
  'きろくを よめなかったよ': ['Không đọc được thành tích', 'Could not read the records'],
  'まえの ランドで もう いちど「おひっこし する」を おしてね。': ['Hãy mở Thế giới Kero cũ và nhấn “Chuyển nhà” lần nữa nhé.', 'Open the old Kero Land and tap “Move now” again.']
});

// The big title, one line per row (each letter hops on its own).
var LAND_LOGO = { ja: ['ケロちゃん', 'ランド'], vi: ['Thế giới', 'Kero'], en: ['Kero', 'Land'], ko: ['케로', '랜드'] };
